name: e2e
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  analyzer: ">=6.9.0 <8.0.0"
  analyzer_buffer: ^0.0.4
  build: ^2.5.0
  build_config: ^1.1.0
  collection: ^1.15.0
  meta: ^1.17.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^3.0.0
  matcher: ^0.12.14
  test: ^1.21.0
